export const img = (id, w = 900) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;

export const INDUSTRIES = [
  {
    id: "horeca",
    name: "HORECA",
    short: "Restaurantes, bares, cafés y catering",
    photo: "photo-1552566626-52f8b828add9",
    photoAlt: "Salón de un restaurante moderno con barra y mesas dispuestas",
    headline: "Controla la merma y el costo real de cada plato",
    metrics: [
      "Control de mermas y desperdicio de insumos",
      "Costo de plato y receta estándar actualizada",
      "Margen por cubierto y ticket promedio",
      "Variación de flujo entre días de semana y fin de semana",
    ],
    kpi: { label: "Margen por cubierto", value: "32%" },
    secondary: { label: "Merma objetivo", value: "< 4%" },
  },
  {
    id: "hoteles",
    name: "Hoteles y Hostales",
    short: "Alojamiento y temporadas",
    photo: "photo-1566073771259-6a8506099945",
    photoAlt: "Hotel boutique con piscina y terraza al atardecer",
    headline: "Proyecta tu ocupación y el equilibrio por habitación",
    metrics: [
      "Proyección de ocupación promedio mensual",
      "Impacto real de temporada alta vs. temporada baja",
      "Punto de equilibrio por habitación disponible",
      "Tarifa mínima rentable (ADR de seguridad)",
    ],
    kpi: { label: "Ocupación de equilibrio", value: "48%" },
    secondary: { label: "Tarifa mínima", value: "ADR seguro" },
  },
  {
    id: "panaderias",
    name: "Panaderías y Pastelerías",
    short: "Producción por lotes",
    photo: "photo-1509440159596-0249088772ff",
    photoAlt: "Panes artesanales recién horneados sobre la mesa de trabajo",
    headline: "Cada lote de producción con su punto de equilibrio",
    metrics: [
      "Control de materias primas y variación de precios",
      "Turnos de producción y costo de horneada",
      "Punto de equilibrio por lote de producción",
      "Rotación de producto fresco y devoluciones",
    ],
    kpi: { label: "Equilibrio por lote", value: "126 uds" },
    secondary: { label: "Costo materia prima", value: "38%" },
  },
  {
    id: "barberias",
    name: "Barberías y Estética",
    short: "Servicios por silla",
    photo: "photo-1503951914875-452162b0f3f1",
    photoAlt: "Barbero atendiendo a un cliente en una barbería moderna",
    headline: "Comisiones por silla sin perder margen",
    metrics: [
      "Gestión de comisiones por silla y por barbero",
      "Costo de insumos por servicio",
      "Margen por servicio y por combo",
      "Citas mínimas diarias para cubrir el fijo",
    ],
    kpi: { label: "Margen por servicio", value: "44%" },
    secondary: { label: "Citas/día de equilibrio", value: "11" },
  },
  {
    id: "veterinarias",
    name: "Veterinarias y Pet Shops",
    short: "Servicios médicos + retail",
    photo: "photo-1628009368231-7bb7cfcb0def",
    photoAlt: "Profesional de una veterinaria revisando a un gato en consulta",
    headline: "Equilibra consulta médica y venta de retail",
    metrics: [
      "Balance entre servicios médicos de alto margen y retail",
      "Margen por consulta, cirugía y vacunación",
      "Rotación de alimento y accesorios",
      "Punto de equilibrio mixto (servicio + producto)",
    ],
    kpi: { label: "Margen servicios", value: "58%" },
    secondary: { label: "Margen retail", value: "22%" },
  },
  {
    id: "retail",
    name: "Otros Comercios / Retail",
    short: "Tiendas, librerías y minimercados",
    photo: "photo-1441986300917-64674bd600d8",
    photoAlt: "Tienda de retail con estanterías y vitrinas organizadas",
    metrics: [
      "Rotación de inventario por categoría",
      "Margen bruto acumulado y capital inmovilizado",
      "Punto de equilibrio por metro cuadrado",
      "Impacto de descuentos y liquidaciones en el flujo",
    ],
    headline: "Rotación de inventario y margen bruto acumulado",
    kpi: { label: "Rotación objetivo", value: "6,2x" },
    secondary: { label: "Margen bruto", value: "34%" },
  },
];
